#!/bin/bash

ETH=$1


if [ "$ETH" = "" ];then

	/usr/bin/samba-tool domain provision --use-rfc2307 --interactive 
else 

	samba-tool domain provision --use-rfc2307 --option="interfaces=lo $ETH" --option="bind interfaces only=yes" --interactive 


fi

exit 0

